
using System;
using System.IO;
using System.Globalization;
using System.Text;
using System.Collections.Generic;

public class StepExporter
{
    public void Export(ModelRoot model, string path)
    {
        using var w = new StreamWriter(path, false, Encoding.ASCII);
        w.WriteLine("ISO-10303-21;");
        w.WriteLine("HEADER;");
        w.WriteLine("FILE_DESCRIPTION(('Generated by SimpleSatParser'),'2;1');");
        w.WriteLine("FILE_NAME('out','',(''),'SimpleSatParser','', '','');");
        w.WriteLine("FILE_SCHEMA(('AUTOMOTIVE_DESIGN_CC2'));");
        w.WriteLine("ENDSEC;");
        w.WriteLine("DATA;");

        int sid = 1;
        var idMap = new Dictionary<int, int>();

        // экспорт точек/направлений/позиций
        foreach (var e in model.Entities)
        {
            switch (e)
            {
                case Vertex v:
                    idMap[v.Id] = sid++;
                    w.WriteLine($"#{idMap[v.Id]} = CARTESIAN_POINT('{v.Id}', ({v.P.X.ToString(CultureInfo.InvariantCulture)}, {v.P.Y.ToString(CultureInfo.InvariantCulture)}, {v.P.Z.ToString(CultureInfo.InvariantCulture)}));");
                    break;
                case StraightCurve sc:
                    idMap[sc.Id] = sid++;
                    w.WriteLine($"#{idMap[sc.Id]} = DIRECTION('{sc.Id}', ({sc.Dir.X.ToString(CultureInfo.InvariantCulture)}, {sc.Dir.Y.ToString(CultureInfo.InvariantCulture)}, {sc.Dir.Z.ToString(CultureInfo.InvariantCulture)}));");
                    break;
                case PlaneSurface ps:
                    idMap[ps.Id] = sid++;
                    w.WriteLine($"#{idMap[ps.Id]} = AXIS2_PLACEMENT_3D('{ps.Id}', CARTESIAN_POINT('', ({ps.Origin.X.ToString(CultureInfo.InvariantCulture)}, {ps.Origin.Y.ToString(CultureInfo.InvariantCulture)}, {ps.Origin.Z.ToString(CultureInfo.InvariantCulture)})), DIRECTION('',({ps.Normal.X.ToString(CultureInfo.InvariantCulture)}, {ps.Normal.Y.ToString(CultureInfo.InvariantCulture)}, {ps.Normal.Z.ToString(CultureInfo.InvariantCulture)})), DIRECTION('',(0,0,1)));");
                    break;
            }
        }

        // ребра
        foreach (var e in model.Entities)
        {
            if (e is Edge ed)
            {
                idMap[ed.Id] = sid++;
                var startRef = ed.VStartId.HasValue && idMap.ContainsKey(ed.VStartId.Value) ? $"#{idMap[ed.VStartId.Value]}" : "$";
                var endRef = ed.VEndId.HasValue && idMap.ContainsKey(ed.VEndId.Value) ? $"#{idMap[ed.VEndId.Value]}" : "$";
                var curveRef = ed.Curve != null && idMap.ContainsKey(ed.Curve.Id) ? $"#{idMap[ed.Curve.Id]}" : "$";
                w.WriteLine($"#{idMap[ed.Id]} = EDGE_CURVE('{ed.Id}', {startRef}, {endRef}, {curveRef}, .T.);");
            }
        }

        // лица
        foreach (var e in model.Entities)
        {
            if (e is Face f)
            {
                idMap[f.Id] = sid++;
                var surfRef = f.Surface != null && idMap.ContainsKey(f.Surface.Id) ? $"#{idMap[f.Surface.Id]}" : "$";
                var bounds = new List<string>();
                if (f.OuterLoop != null)
                {
                    foreach (var cid in f.OuterLoop.CoedgeIds)
                    {
                        var co = model.Reg.Get<Coedge>(cid);
                        if (co != null && idMap.ContainsKey(co.EdgeId))
                            bounds.Add($"#{idMap[co.EdgeId]}");
                    }
                }
                var boundList = bounds.Count > 0 ? "(" + string.Join(",", bounds) + ")" : "$";
                w.WriteLine($"#{idMap[f.Id]} = ADVANCED_FACE('{f.Id}', {boundList}, {surfRef}, .{(f.Reversed ? "T" : "F")}.);");

            }
        }

        w.WriteLine("ENDSEC;");
        w.WriteLine("END-ISO-10303-21;");
    }
}
